# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_base_version=1.21.3
minecraft_version=1.21.3
yarn_mappings=1.21.3+build.2
loader_version=0.16.9
# Mod Properties
mod_version=0.4.2
maven_group=com.glisco
archives_base_name=deathlog-yuzi
# Dependencies
fabric_version=0.107.3+1.21.3

# https://github.com/emilyploszaj/trinkets/releases
trinkets_version=3.10.0

# https://maven.ladysnake.org/#/releases/dev/onyxstudios/cardinal-components-api/cardinal-components-api/cardinal-components-base
cca_version=6.2.0

# https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
modmenu_version=12.0.0-beta.1

# https://maven.wispforest.io/io/wispforest/owo-lib/
owo_version=0.12.18+1.21.2

